spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/mutbooks?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: roger3495
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create